version: '3.8'

services:
  app:
    image: 'dojo-currencies:latest'
    container_name: app_container
    build:
      context: ..
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL82Dialect
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.hibernate.show-sql=true
      - spring.jpa.properties.hibernate.format_sql=true
      - spring.datasource.url=jdbc:postgresql://db:5432/dojo-currencies
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - nbp.api.url=http://api.nbp.pl/api/exchangerates/tables/c
  db:
    image: 'postgres:13.1-alpine'
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dojo-currencies
    ports:
      - "5432:5432"
    restart: always
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: pgadmin4_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    restart: always